-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 15:56:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vacation_request
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vacation_request` ;

-- -----------------------------------------------------
-- Schema vacation_request
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vacation_request` DEFAULT CHARACTER SET utf8 ;
USE `vacation_request` ;

-- -----------------------------------------------------
-- Table `vacation_request`.`Mitarbeiter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vacation_request`.`Mitarbeiter` ;

CREATE TABLE IF NOT EXISTS `vacation_request`.`Mitarbeiter` (
  `idMitarbeiter` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `E-Mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMitarbeiter`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
